// =====================================================================
// Evidence Type Definitions
// Video/replay evidence for incident review, protests, and appeals
// =====================================================================

/**
 * Evidence visibility levels
 */
export type EvidenceVisibility =
    | 'INTERNAL_ONLY'    // System use only
    | 'STEWARDS_ONLY'    // Only visible to stewards
    | 'LEAGUE_ADMIN'     // Visible to league admins and above
    | 'DRIVER_VISIBLE';  // Visible to involved drivers

/**
 * Evidence type classification
 */
export type EvidenceType =
    | 'UPLOAD'           // Uploaded video file (MP4/WebM)
    | 'EXTERNAL_URL'     // External link (YouTube/Streamable)
    | 'IRACING_REPLAY_REF'; // iRacing replay reference

/**
 * Evidence source categories for UI tabs
 */
export type EvidenceSource =
    | 'primary'      // Main/official evidence
    | 'onboard'      // Onboard camera footage
    | 'chase'        // Chase camera / following car
    | 'broadcast'    // Broadcast/TV camera
    | 'external';    // User-submitted external content

/**
 * Steward assessment of evidence
 */
export type EvidenceAssessment =
    | 'PENDING'
    | 'ACCEPTED'
    | 'NOT_ACCEPTED'
    | 'INSUFFICIENT';

/**
 * Core evidence asset record
 */
export interface EvidenceAsset {
    /** Unique evidence identifier */
    id: string;
    /** Evidence type */
    type: EvidenceType;
    /** Owner league ID (multi-tenant isolation) */
    ownerLeagueId: string;
    /** User who uploaded/added this evidence */
    uploadedByUserId: string;
    /** Uploader display name */
    uploadedByName?: string;
    /** Title/description */
    title: string;
    /** Additional notes */
    notes?: string;
    /** Evidence source category */
    source: EvidenceSource;
    /** Visibility level */
    visibility: EvidenceVisibility;
    /** Steward assessment status */
    assessment: EvidenceAssessment;
    /** Assessment notes from steward */
    assessmentNotes?: string;

    // Linked entities
    /** Linked incident IDs */
    incidentIds: string[];
    /** Linked case IDs */
    caseIds: string[];
    /** Linked protest IDs */
    protestIds: string[];

    // Type-specific data
    /** Upload details (when type = UPLOAD) */
    upload?: EvidenceUpload;
    /** External URL details (when type = EXTERNAL_URL) */
    externalUrl?: EvidenceExternalUrl;
    /** Replay reference details (when type = IRACING_REPLAY_REF) */
    replayRef?: EvidenceReplayRef;

    // Key moments for navigation
    /** Auto-generated or manual key moment timestamps */
    keyMoments?: EvidenceKeyMoment[];

    createdAt: Date;
    updatedAt: Date;
}

/**
 * Uploaded file evidence details
 */
export interface EvidenceUpload {
    /** Storage provider identifier */
    storageProvider: 'DO_SPACES' | 'S3' | 'LOCAL';
    /** File key/path in storage */
    fileKey: string;
    /** MIME type */
    mimeType: string;
    /** File size in bytes */
    sizeBytes: number;
    /** Video duration in seconds (if available) */
    durationSeconds?: number;
    /** Thumbnail file key (optional) */
    thumbnailKey?: string;
    /** Pre-signed URL (populated on fetch, not stored) */
    signedUrl?: string;
    /** Signed URL expiration */
    signedUrlExpiresAt?: Date;
}

/**
 * External URL evidence details
 */
export interface EvidenceExternalUrl {
    /** External URL */
    url: string;
    /** Provider hint for embedding */
    providerHint: 'youtube' | 'streamable' | 'drive' | 'other';
    /** Embedded player URL (if different) */
    embedUrl?: string;
}

/**
 * iRacing replay reference details
 */
export interface EvidenceReplayRef {
    /** Simulation type */
    sim: 'iracing';
    /** iRacing session/event ID */
    eventId: string;
    /** iRacing subsession ID */
    subsessionId?: string;
    /** Lap number */
    lap: number;
    /** Corner/sector identifier (optional) */
    corner?: string;
    /** Timecode hint (e.g., "1:23:45") */
    timecodeHint?: string;
    /** Seconds before incident to start */
    offsetSecondsBefore: number;
    /** Seconds after incident to show */
    offsetSecondsAfter: number;
    /** Recommended camera */
    cameraHint?: string;
    /** Additional viewing notes */
    viewingNotes?: string;
}

/**
 * Key moment marker for video navigation
 */
export interface EvidenceKeyMoment {
    /** Moment identifier */
    id: string;
    /** Display label */
    label: string;
    /** Time offset in seconds from start */
    offsetSeconds: number;
    /** Moment type for styling */
    type: 'pre_incident' | 'contact' | 'post_incident' | 'rejoin' | 'custom';
    /** Auto-generated vs manual */
    isAutoGenerated: boolean;
}

// =====================================================================
// API Request/Response Types
// =====================================================================

/**
 * Request pre-signed upload URL
 */
export interface EvidenceUploadRequest {
    /** File name */
    fileName: string;
    /** MIME type */
    mimeType: string;
    /** File size in bytes */
    sizeBytes: number;
    /** Evidence title */
    title: string;
    /** Evidence source category */
    source: EvidenceSource;
    /** Initial visibility */
    visibility?: EvidenceVisibility;
    /** Link to incident ID */
    incidentId?: string;
    /** Link to case ID */
    caseId?: string;
    /** Link to protest ID */
    protestId?: string;
}

/**
 * Pre-signed upload URL response
 */
export interface EvidenceUploadResponse {
    /** Evidence asset ID (created pending upload) */
    evidenceId: string;
    /** Pre-signed upload URL */
    uploadUrl: string;
    /** Upload expiration time */
    expiresAt: Date;
    /** Storage file key */
    fileKey: string;
}

/**
 * Complete upload notification
 */
export interface EvidenceUploadCompleteRequest {
    /** Evidence ID from upload request */
    evidenceId: string;
    /** Optional duration detected by client */
    durationSeconds?: number;
}

/**
 * Add external URL evidence
 */
export interface EvidenceExternalUrlRequest {
    /** External URL */
    url: string;
    /** Evidence title */
    title: string;
    /** Notes */
    notes?: string;
    /** Evidence source category */
    source: EvidenceSource;
    /** Visibility */
    visibility?: EvidenceVisibility;
    /** Link to incident */
    incidentId?: string;
    /** Link to case */
    caseId?: string;
    /** Link to protest */
    protestId?: string;
}

/**
 * Add iRacing replay reference
 */
export interface EvidenceReplayRefRequest {
    /** Event/session ID */
    eventId: string;
    /** Subsession ID */
    subsessionId?: string;
    /** Lap number */
    lap: number;
    /** Corner/sector */
    corner?: string;
    /** Timecode hint */
    timecodeHint?: string;
    /** Evidence title */
    title: string;
    /** Notes */
    notes?: string;
    /** Seconds before (default 10) */
    offsetSecondsBefore?: number;
    /** Seconds after (default 10) */
    offsetSecondsAfter?: number;
    /** Camera hint */
    cameraHint?: string;
    /** Visibility */
    visibility?: EvidenceVisibility;
    /** Link to incident */
    incidentId?: string;
}

/**
 * Link/unlink evidence to entities
 */
export interface EvidenceLinkRequest {
    /** Incident IDs to link */
    incidentIds?: string[];
    /** Case IDs to link */
    caseIds?: string[];
    /** Protest IDs to link */
    protestIds?: string[];
}

/**
 * Update evidence metadata
 */
export interface EvidenceUpdateRequest {
    /** Updated title */
    title?: string;
    /** Updated notes */
    notes?: string;
    /** Updated source category */
    source?: EvidenceSource;
    /** Updated visibility */
    visibility?: EvidenceVisibility;
    /** Steward assessment */
    assessment?: EvidenceAssessment;
    /** Assessment notes */
    assessmentNotes?: string;
}

/**
 * List evidence filters
 */
export interface ListEvidenceParams {
    /** Filter by incident ID */
    incidentId?: string;
    /** Filter by case ID */
    caseId?: string;
    /** Filter by protest ID */
    protestId?: string;
    /** Filter by type */
    type?: EvidenceType;
    /** Filter by source */
    source?: EvidenceSource;
    /** Page number */
    page?: number;
    /** Page size */
    pageSize?: number;
}

// =====================================================================
// Audit Log Types
// =====================================================================

/**
 * Evidence audit log action types
 */
export type EvidenceAuditAction =
    | 'UPLOADED'
    | 'EXTERNAL_ADDED'
    | 'REPLAY_REF_ADDED'
    | 'LINKED'
    | 'UNLINKED'
    | 'VISIBILITY_CHANGED'
    | 'ASSESSMENT_CHANGED'
    | 'DELETED';

/**
 * Evidence audit log entry
 */
export interface EvidenceAuditEntry {
    id: string;
    evidenceId: string;
    action: EvidenceAuditAction;
    performedByUserId: string;
    performedByName?: string;
    details: Record<string, unknown>;
    timestamp: Date;
}
